#theme: jekyll-theme-slate
#theme: jekyll-theme-hacker
theme: jekyll-theme-minimal
title: Security Mindset Blog
description: Security Research, Reverse Engineering, and Code

plugins:
  - jekyll-postfiles